# Generated by Django 6.0.5 on 2026-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='capabilities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='confidence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='evidence_summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='company',
            name='has_run_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='last_analyzed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='maturity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='raw_evidence',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='score_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='company',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verdict',
            field=models.BooleanField(default=False),
        ),
    ]
